[manager]
ratio = [1, 4, 3]
sort_by = "modified"
sort_sensitive = false
sort_reverse = true
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""

[opener]
edit = [
    { run = 'nvim "$@"', desc = "Neovim", for = "windows" },
]
open = [
    { run = 'start "" "$1"', desc = "Open", for = "windows" },
]
reveal = [
    { run = 'explorer /select,"$1"', desc = "Reveal", for = "windows" },
]
extract = [
    { run = '7z x "$1"', desc = "Extract here", for = "windows" },
]
play = [
    { run = 'start "" "$1"', desc = "Play", for = "windows" },
]

[open]
rules = [
    { name = "*/", use = "edit" },
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "*/javascript", use = "edit" },
    { mime = "image/*", use = "open" },
    { mime = "video/*", use = "play" },
    { mime = "audio/*", use = "play" },
    { mime = "inode/directory", use = "open" },
    { name = "*.zip", use = "extract" },
    { name = "*.7z", use = "extract" },
    { name = "*.rar", use = "extract" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[plugin]

[input]
cursor_blink = true

[log]
enabled = false
